# Generated by Django 2.2.5 on 2019-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191120_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки'),
        ),
    ]
