# Generated by Django 2.2.5 on 2019-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20191128_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.FileField(upload_to='attachments', verbose_name='Ссылка на вложение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, null=True, verbose_name='Последнее сообщение'),
        ),
    ]
