# Generated by Django 2.2.5 on 2020-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191205_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.IntegerField(blank=True, null=True, verbose_name='Последнее сообщение'),
        ),
    ]
